### 이미지 데이터 분류
- 데이터 : sklearn.datasets의 MNIST ==> 디지털 0~9 손글씨 데이터셋
- 피쳐 : 이미지 픽셀 수, 28 * 28 = 784
- 타겟 : 0~9, 총 10개
- 학습유형 : 지도학습 + 

## (1) 모듈 로딩 및 데이터 준비 <hr>

In [1]:
# 모듈 로딩
from sklearn.datasets import fetch_openml

In [2]:
# 데이터 로딩
mnist=fetch_openml(name='mnist_784')

/Users/sml/anaconda3/envs/EXAM_ML/lib/python3.9/site-packages/sklearn/datasets/_openml.py:1002: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


In [3]:
mnist.data.shape, mnist.target.shape

((70000, 784), (70000,))

In [4]:
mnist.data.describe()

pixel1   pixel2   pixel3   pixel4   pixel5   pixel6   pixel7   pixel8  \
count  70000.0  70000.0  70000.0  70000.0  70000.0  70000.0  70000.0  70000.0   
mean       0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
std        0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
min        0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
25%        0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
50%        0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
75%        0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
max        0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   

        pixel9  pixel10  ...      pixel775      pixel776      pixel777  \
count  70000.0  70000.0  ...  70000.000000  70000.000000  70000.000000   
mean       0.0      0.0  ...      0.197414      0.099543      0.046629   
std        0.0      0.0  ...      5.991206      4.256304      2.783732   
min        0.0      0.0  ...      0.000000      0.000000      0.000000   
25%        0.0      0.0  ...      0.000000      0.000000      0.000000   
50%        0.0      0.0  ...      0.000000      0.000000      0.000000   
75%        0.0      0.0  ...      0.000000      0.000000      0.000000   
max        0.0      0.0  ...    254.000000    254.000000    253.000000   

           pixel778      pixel779      pixel780  pixel781  pixel782  pixel783  \
count  70000.000000  70000.000000  70000.000000   70000.0   70000.0   70000.0   
mean       0.016614      0.012957      0.001714       0.0       0.0       0.0   
std        1.561822      1.553796      0.320889       0.0       0.0       0.0   
min        0.000000      0.000000      0.000000       0.0       0.0       0.0   
25%        0.000000      0.000000      0.000000       0.0       0.0       0.0   
50%        0.000000      0.000000      0.000000       0.0       0.0       0.0   
75%        0.000000      0.000000      0.000000       0.0       0.0       0.0   
max      253.000000    254.000000     62.000000       0.0       0.0       0.0   

       pixel784  
count   70000.0  
mean        0.0  
std         0.0  
min         0.0  
25%         0.0  
50%         0.0  
75%         0.0  
max         0.0  

[8 rows x 784 columns]

### [2] 데이터 전처리 <hr>
- 이미지 픽셀값 0~1로 스케일링

In [5]:
featureDF = mnist.data

In [7]:
featureDF = featureDF/255
featureDF.describe()

pixel1   pixel2   pixel3   pixel4   pixel5   pixel6   pixel7   pixel8  \
count  70000.0  70000.0  70000.0  70000.0  70000.0  70000.0  70000.0  70000.0   
mean       0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
std        0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
min        0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
25%        0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
50%        0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
75%        0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
max        0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   

        pixel9  pixel10  ...      pixel775      pixel776      pixel777  \
count  70000.0  70000.0  ...  70000.000000  70000.000000  70000.000000   
mean       0.0      0.0  ...      0.000774      0.000390      0.000183   
std        0.0      0.0  ...      0.023495      0.016691      0.010917   
min        0.0      0.0  ...      0.000000      0.000000      0.000000   
25%        0.0      0.0  ...      0.000000      0.000000      0.000000   
50%        0.0      0.0  ...      0.000000      0.000000      0.000000   
75%        0.0      0.0  ...      0.000000      0.000000      0.000000   
max        0.0      0.0  ...      0.996078      0.996078      0.992157   

           pixel778      pixel779      pixel780  pixel781  pixel782  pixel783  \
count  70000.000000  70000.000000  70000.000000   70000.0   70000.0   70000.0   
mean       0.000065      0.000051      0.000007       0.0       0.0       0.0   
std        0.006125      0.006093      0.001258       0.0       0.0       0.0   
min        0.000000      0.000000      0.000000       0.0       0.0       0.0   
25%        0.000000      0.000000      0.000000       0.0       0.0       0.0   
50%        0.000000      0.000000      0.000000       0.0       0.0       0.0   
75%        0.000000      0.000000      0.000000       0.0       0.0       0.0   
max        0.992157      0.996078      0.243137       0.0       0.0       0.0   

       pixel784  
count   70000.0  
mean        0.0  
std         0.0  
min         0.0  
25%         0.0  
50%         0.0  
75%         0.0  
max         0.0  

[8 rows x 784 columns]

- 타겟 확인

In [10]:
targetDF = mnist.target
targetDF.unique()

['5', '0', '4', '1', '9', '2', '3', '6', '7', '8']
Categories (10, object): ['0', '1', '2', '3', ..., '6', '7', '8', '9']

In [16]:
targetDF = targetDF.astype('int')
targetDF.unique()

array([5, 0, 4, 1, 9, 2, 3, 6, 7, 8])

### [3] 기계학습용 데이터셋 준비 <hr>
- 학습용, 검증용, 테스트용 3개 데이터셋 준비

In [17]:
# 모듈 로딩

from sklearn.model_selection import train_test_split

In [18]:
featureDF.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70000 entries, 0 to 69999
Columns: 784 entries, pixel1 to pixel784
dtypes: float64(784)
memory usage: 418.7 MB


In [20]:
# 학습용 & 테스트용 분리 => MNIST database에서 제공한 6만개와 1만개

# X_train, x_test, y_train, y_test = train_test_split(featureDF,
#                                                     targetDF,
#                                                     stratify=targetDF
#                                                     )
# 사용 안하고

X_train = featureDF.iloc[:60000]
y_train = targetDF[:60000]
x_test = featureDF.iloc[60000:]
y_test = targetDF[60000:]

print(f'X_train : {X_train.shape}, y_train : {y_train.shape}')
print(F'x_test : {x_test.shape}, y_test : {y_test.shape}')

X_train : (60000, 784), y_train : (60000,)
x_test : (10000, 784), y_test : (10000,)


In [21]:
# 학습용 & 검증용 분리 => 학습용 데이터셋에서 일부를 검증용으로 준비
# 검증용 - 학습 시 모델 최적화가 잘 되는 지 검사하는 데이터 셋
# 검증용 - ( 학습용 데이터 에포크 후 중간 시험 ) 과정을 반복해서 학습용=검증용 점수가 되면 실제 테스트

X_train, x_val, y_train, y_val = train_test_split(X_train,
                                                  y_train,
                                                  test_size=0.3,
                                                  stratify=y_train,
                                                  random_state=5)

In [22]:
print(f'X_train : {X_train.shape}, y_train : {y_train.shape}')
print(F'x_val : {x_val.shape}, y_test : {y_val.shape}')

X_train : (42000, 784), y_train : (42000,)
x_val : (18000, 784), y_test : (18000,)


### [4] 학습 진행 <hr>

#### [4-1] 분류 방법 : LogisticRegression

In [29]:
from sklearn.linear_model import LogisticRegression

lr_model = LogisticRegression(max_iter=10000)
lr_model.fit(X_train, y_train)

LogisticRegression(max_iter=10000)

In [31]:
train_score = lr_model.score(X_train, y_train)
val_score = lr_model.score(x_val, y_val)
test_score = lr_model.score(x_test, y_test)


print(f'train_score : {train_score}, val_score : {val_score}, test_score : {test_score}')
print(lr_model.n_iter_)

train_score : 0.9429285714285714, val_score : 0.9173888888888889, test_score : 0.9237
[722]


### [5] 학습 모델 성능 평가 <hr>

In [32]:
## 분류 모델 성능평가 => accuracy, precision, recall, f1-score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

In [34]:
# 클래스 비율
y_train.value_counts(), y_test.value_counts()

(class
 1    4719
 7    4385
 3    4292
 2    4171
 9    4164
 0    4146
 6    4143
 8    4096
 4    4089
 5    3795
 Name: count, dtype: int64,
 class
 1    1135
 2    1032
 7    1028
 3    1010
 9    1009
 4     982
 0     980
 8     974
 6     958
 5     892
 Name: count, dtype: int64)

#### [4-2] 확률적경사하강법 기반 학습 <hr>
- 대량의 데이터를 학습 시 랜덤으로 데이터셋 1개 추출해서 학습 진행 => 최적화
- 장점 : 속도 빨라짐
- 단점 : 정확도 떨어짐
- 개선 : 일정 데이터를 묶어서 학습 후 최적화 진행 => 미니배치
- 학습모델을 선정 필요

In [35]:
# 모듈 로딩 SGDClassifier => 분류 알고리즘을 SGD방법으로 학습 진행
from sklearn.linear_model import SGDClassifier

In [38]:
# LogisticRegression 알고리즘으로 학습 진행
lr_sgd = SGDClassifier(loss = 'log_loss', random_state=5)
lr_sgd.fit(X_train,y_train)

SGDClassifier(loss='log_loss', random_state=5)

In [39]:
# 모델 파라미터 확인
print(lr_sgd.n_iter_)

24


In [40]:
# 성능 확인
train_score = lr_sgd.score(X_train, y_train)
val_score = lr_sgd.score(x_val, y_val)
test_score = lr_sgd.score(x_test, y_test)

print(f'train_score : {train_score}, val_score : {val_score}, test_score : {test_score}')

train_score : 0.9197380952380952, val_score : 0.9090555555555555, test_score : 0.9127


In [48]:
print(f'[BEFORE] lr_sgd.coef_ : ==>\n{lr_sgd.coef_}, {lr_sgd.coef_.shape}')
print(f'[BEFORE] lr_sgd.intercept_ : ==>\n{lr_sgd.intercept_}, {lr_sgd.intercept_.shape}')


[BEFORE] lr_sgd.coef_ : ==>
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], (10, 784)
[BEFORE] lr_sgd.intercept_ : ==>
[-7.63353136 -0.98978771 -2.9413531  -4.36759259 -2.28353702  0.13432777
 -4.58279195 -0.85577947 -7.83234866 -4.44128399], (10,)


In [49]:
## 추가된 데이터에 대하여 추가 학습 진행 => 기존 학습으로 최적화 된 상태 유지
import numpy as np

lr_sgd.partial_fit(x_val, y_val, np.unique(y_val))

SGDClassifier(loss='log_loss', random_state=5)